name: Compare Regex Versions
description: Extract and compare version strings from two files using regex patterns

inputs:
  file1:
    description: "Path to the first file"
    required: true
  file1-regex:
    description: 'Perl-compatible regex pattern to extract version from file1 (use \K and lookahead for capture)'
    required: true
  file1-label:
    description: "Human-readable label for file1 (for error messages)"
    required: true

  file2:
    description: "Path to the second file"
    required: true
  file2-regex:
    description: 'Perl-compatible regex pattern to extract version from file2 (use \K and lookahead for capture)'
    required: true
  file2-label:
    description: "Human-readable label for file2 (for error messages)"
    required: true

  error-message:
    description: "Custom error message to display if versions do not match (optional, uses default if not provided)"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Compare versions
      shell: bash
      run: |
        # Extract version from first file
        echo "Extracting version from ${{ inputs.file1 }} using pattern: ${{ inputs.file1-regex }}"
        version1=$(grep -oP '${{ inputs.file1-regex }}' '${{ inputs.file1 }}' | head -1) || version1=""
        if [ -z "$version1" ]; then
          echo "::error file=${{ inputs.file1 }}::Failed to extract version from ${{ inputs.file1-label }} using pattern: ${{ inputs.file1-regex }}"
          echo "ERROR: Failed to extract version from ${{ inputs.file1-label }}" >&2
          echo "  File: ${{ inputs.file1 }}" >&2
          echo "  Pattern: ${{ inputs.file1-regex }}" >&2
          exit 1
        fi
        echo "${{ inputs.file1-label }}: $version1"

        # Extract version from second file
        echo "Extracting version from ${{ inputs.file2 }} using pattern: ${{ inputs.file2-regex }}"
        version2=$(grep -oP '${{ inputs.file2-regex }}' '${{ inputs.file2 }}' | head -1) || version2=""
        if [ -z "$version2" ]; then
          echo "::error file=${{ inputs.file2 }}::Failed to extract version from ${{ inputs.file2-label }} using pattern: ${{ inputs.file2-regex }}"
          echo "ERROR: Failed to extract version from ${{ inputs.file2-label }}" >&2
          echo "  File: ${{ inputs.file2 }}" >&2
          echo "  Pattern: ${{ inputs.file2-regex }}" >&2
          exit 1
        fi
        echo "${{ inputs.file2-label }}: $version2"

        # Compare versions
        if [ "$version1" != "$version2" ]; then
          echo "::error::Version mismatch: ${{ inputs.file1-label }} has \"$version1\" but ${{ inputs.file2-label }} has \"$version2\""
          if [ -n "${{ inputs.error-message }}" ]; then
            echo "::notice::${{ inputs.error-message }}"
          fi
          exit 1
        fi

        echo "✓ Versions are consistent: $version1"
