[files]
extend-exclude = ["**/target/**", "**/Cargo.lock"]

# Allow specific identifiers in code derived from WDK
[default.extend-identifiers]
STATUS_FVE_MOR_FAILED = "STATUS_FVE_MOR_FAILED"
STATUS_MCA_OCCURED = "STATUS_MCA_OCCURED"
STATUS_ND_QUEUE_OVERFLOW = "STATUS_ND_QUEUE_OVERFLOW"
STATUS_TPM_DAA_INPUT_DATA0 = "STATUS_TPM_DAA_INPUT_DATA0"
STATUS_TPM_DAA_INPUT_DATA1 = "STATUS_TPM_DAA_INPUT_DATA1"
STATUS_TPM_DAA_ISSUER_SETTINGS = "STATUS_TPM_DAA_ISSUER_SETTINGS"
STATUS_TPM_DAA_ISSUER_VALIDITY = "STATUS_TPM_DAA_ISSUER_VALIDITY"
STATUS_TPM_DAA_RESOURCES = "STATUS_TPM_DAA_RESOURCES"
STATUS_TPM_DAA_STAGE = "STATUS_TPM_DAA_STAGE"
STATUS_TPM_DAA_TPM_SETTINGS = "STATUS_TPM_DAA_TPM_SETTINGS"
STATUS_TPM_DAA_WRONG_W = "STATUS_TPM_DAA_WRONG_W"
