# regex-automata v0.1.10: matchers v0.1.0 < tracing-subscriber v0.3.19 < cargo-wdk v0.0.1
# regex-automata v0.4.7: bstr v1.11.3 < assert_cmd v2.0.16 < (dev) cargo-wdk
# regex-syntax v0.6.29: regex-automata v0.1.10.
# regex-syntax v0.8.4: regex v1.10.5 < predicates v3.1.3 < mockall v0.13.1 < cargo-wdk v0.0.1
# tracing-subscriber crate needs update to use matchers v0.1^
allowed-duplicate-crates = ["regex-automata", "regex-syntax"]
