[workspace]
git_release_draft = true
pr_draft = true
pr_labels = ["release"]

[changelog]
header = """# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""
protect_breaking_commits = true
