/* automatically generated by rust-bindgen 0.69.4 */

extern "C" {
    pub fn RtlAssert(
        FailedAssertion: PVOID,
        FileName: PVOID,
        LineNumber: ULONG,
        Message: PSTR,
    );
}
