extend = "../crates/wdk-build/rust-driver-makefile.toml"

[env]
CARGO_MAKE_WORKSPACE_EMULATION = true
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = [
  "config-kmdf",
  "config-umdf",
  "config-wdm",
  "customized-config-toml-workspace",
  "mixed-package-kmdf-workspace",
  "umdf-driver-workspace",
  "wdk-macros-tests",
  "wdk-sys-tests",
]
