// Copyright (c) Microsoft Corporation
// License: MIT OR Apache-2.0

//! Direct FFI bindings to HID APIs from the Windows Driver Kit (WDK)
//!
//! This module contains all bindings to functions, constants, methods,
//! constructors and destructors in the following headers: `hidpddi.h`,
//! `hidport.h`, `HidSpiCx/1.0/hidspicx.h`, `kbdmou.h`, `ntdd8042.h`,
//! `hidclass.h`, `hidsdi.h`, `hidpi.h`, `vhf.h`. Types are not included in this
//! module, but are available in the top-level `wdk_sys` module.

#[allow(
    missing_docs,
    reason = "most items in the WDK headers have no inline documentation, so bindgen is unable to \
              generate documentation for their bindings"
)]
mod bindings {
    include!(concat!(env!("OUT_DIR"), "/hid.rs"));
}
#[allow(
    unused_imports,
    reason = "in certain versions of the WDK, there are no functions related to HID that can be \
              generated by bindgen, so the `bindings` module is empty"
)]
pub use bindings::*;
