// Copyright (c) Microsoft Corporation
// License: MIT OR Apache-2.0
#![no_main]
#![deny(warnings)]

#[allow(unused_imports)] // used by code generated by call_unsafe_wdf_function_binding
use wdk_sys::*;

fn foo() {
    unsafe { wdk_macros::call_unsafe_wdf_function_binding!(WdfVerifierDbgBreakPoint) }
}
