name: Install WDK

inputs:
  version:
    description: WDK version to install.
    required: true
  source:
    description: Source to install WDK from (nuget or winget).
    required: true
  arch:
    description: Host architecture (x64 or ARM64).
    required: true

runs:
  using: "composite"
  steps:
    - name: Install WDK
      shell: pwsh
      run: |
        $version = '${{ inputs.version }}'
        if ($version -notmatch '^10\.0\.\d{5}(\.\d{1,4})?$') {
          Write-Error "Invalid version format: $version. Expected format: 10.0.[5 digit number].[0-4 digit number]"
          exit 1
        }
        $sdk_version = ($version.Split('.')[0..2]) -join '.'
        
        $source = '${{ inputs.source }}'
        if ($source -ne 'nuget' -and $source -ne 'winget') {
          Write-Error "Invalid source: $source. Supported sources are 'nuget' and 'winget'."
          exit 1
        }

        if ($source -eq 'nuget') {
          $wdkDir = "C:\NugetContentRoot"
          if (Test-Path $wdkDir) {
            Write-Host "Output directory $wdkDir already exists. Removing it..."
            Remove-Item -Recurse -Force $wdkDir
          }
          Write-Host "Trying to install WDK version $version using nuget CLI..."
          nuget install Microsoft.Windows.WDK.$arch -Version $version -Source https://api.nuget.org/v3/index.json -NonInteractive -OutputDirectory $wdkDir
          Write-Host "WDK installed to $wdkDir"
          if (-not (Test-Path $wdkDir)) {
            Write-Error "Failed to install dependencies to $wdkDir. Please check the WDK version and source."
            exit 1
          }
          Write-Host "Setting WDKContentRoot environment variable to $WDKContentRoot..."
          $WDKContentRoot = "$wdkDir\Microsoft.Windows.WDK.$arch.$version\c"
          Write-Output "WDKContentRoot=$WDKContentRoot" >> $env:GITHUB_ENV

          Write-Host "Setting WDK_BUILD_SDK_VERSION environment variable to $sdk_version..."
          Write-Output "WDK_BUILD_SDK_VERSION=$sdk_version.0" >> $env:GITHUB_ENV

        } else {
          Write-Host "Using Winget to install WDK version $version..."
          $wdk = "Microsoft.WindowsWDK.$version"
          if ((Get-WinGetPackage -Id $wdk -Source winget -MatchOption Equals).Id -eq '$wdk') {
            Write-Host "$wdk is already installed. Attempting to update..."
            Update-WinGetPackage -Id $wdk -Source winget -MatchOption Equals -Mode Silent -Force
          } else {
            Write-Host "Installing $wdk..."
            Install-WinGetPackage -Id $wdk -Source winget -MatchOption Equals -Mode Silent -Force
          }
          Write-Host "Setting WDK_BUILD_SDK_VERSION environment variable to $sdk_version..."
          Write-Output "WDK_BUILD_SDK_VERSION=$sdk_version.0" >> $env:GITHUB_ENV
        }
