name: Install WDK
description: "Install Windows Driver Kit via NuGet or WinGet with robust error handling and verification"

inputs:
  version:
    description: "WDK version to install. Format: 10.0.XXXXX or 10.0.XXXXX.YYYY. If QFE (4th component) is omitted, the latest available QFE is selected."
    required: true
  source:
    description: "Source to install WDK from (nuget or winget)."
    required: false
    default: "nuget"
  # required to set WDKBinRoot and WDKToolRoot based on the host architecture when using nuget
  host:
    description: "Host architecture (amd64 or arm64). Required when using NuGet source."
    required: false
  # required to set WDKContentRoot based on the target architecture when using nuget
  target:
    description: "Target architecture (amd64 or arm64). Required when using NuGet source."
    required: false

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest
        $ErrorActionPreference = 'Stop'

        $source = '${{ inputs.source }}'
        $version = '${{ inputs.version }}'
        $hostArch = '${{ inputs.host }}'
        $targetArch = '${{ inputs.target }}'

        Write-Host "Validating WDK installation inputs..."
        Write-Host "Source: $source"
        Write-Host "Version: $version"
        Write-Host "Host: $hostArch"
        Write-Host "Target: $targetArch"

        # Validate source
        if ($source -notin @('nuget', 'winget')) {
            throw "Invalid source: $source. Must be 'nuget' or 'winget'."
        }

        # Validate version format
        if ($version -notmatch '^10\.0\.\d{5}(\.\d{1,4})?$') {
            throw "Invalid version format: $version. Expected format: 10.0.XXXXX or 10.0.XXXXX.YYYY"
        }

        # Validate architecture inputs for NuGet
        if ($source -eq 'nuget') {
            if ([string]::IsNullOrWhiteSpace($hostArch) -or $hostArch -notin @('amd64', 'arm64')) {
                throw "Invalid or missing host architecture: '$hostArch'. Must be 'amd64' or 'arm64' when using NuGet source."
            }
            if ([string]::IsNullOrWhiteSpace($targetArch) -or $targetArch -notin @('amd64', 'arm64')) {
                throw "Invalid or missing target architecture: '$targetArch'. Must be 'amd64' or 'arm64' when using NuGet source."
            }
        }

        # Validate that host and target are not provided when using WinGet
        if ($source -eq 'winget') {
            if (-not [string]::IsNullOrWhiteSpace($hostArch)) {
                throw "Host architecture should not be specified when using WinGet source. WinGet handles architecture automatically."
            }
            if (-not [string]::IsNullOrWhiteSpace($targetArch)) {
                throw "Target architecture should not be specified when using WinGet source. WinGet handles architecture automatically."
            }
        }

        Write-Host "✅ Input validation passed"

    - name: Install WDK via NuGet
      if: inputs.source == 'nuget'
      shell: pwsh
      run: |
        # Optimization: Set strict mode and error handling
        Set-StrictMode -Version Latest
        $ErrorActionPreference = 'Stop'
        $ProgressPreference = 'SilentlyContinue'

        # Input validation and normalization
        $hostArch = switch ('${{ inputs.host }}') {
            'amd64' { 'x64' }
            'arm64' { 'ARM64' }
        }
        $targetArch = switch ('${{ inputs.target }}') {
            'amd64' { 'x64' }
            'arm64' { 'ARM64' }
        }
        $inputVersion = '${{ inputs.version }}'
        $versionParts = $inputVersion.Split('.')
        $sdkVersion = $versionParts[0..2] -join '.'

        if ($versionParts.Length -eq 3) {
            # No QFE specified, find the latest QFE for this base version
            Write-Host "No QFE specified, searching for latest QFE for version $inputVersion..."
            try {
                Write-Host "Trying NuGet API..."
                $nugetApiUrl = "https://api.nuget.org/v3-flatcontainer/microsoft.windows.wdk.x64/index.json"
                $response = Invoke-RestMethod -Uri $nugetApiUrl -TimeoutSec 30
                $availableVersions = @($response.versions | Where-Object { $_ -match '^\d+\.\d+\.\d+\.\d+$' })
                Write-Host "Found $(@($availableVersions).Count) versions using NuGet API"

                # Filter versions that match the base version and find the latest QFE
                $matchingVersions = @($availableVersions | Where-Object { $_.StartsWith("$inputVersion.") })
                if (@($matchingVersions).Count -eq 0) {
                    Write-Warning "No QFE versions found for base version $inputVersion, using base version..."
                    $version = $inputVersion
                } else {
                    $version = $matchingVersions | Sort-Object { [System.Version]$_ } | Select-Object -Last 1
                    Write-Host "Found latest QFE version: $version"
                }
            } catch {
                Write-Warning "Failed to query NuGet for latest QFE version: $_"
                Write-Host "Using input version $inputVersion without QFE lookup"
                $version = $inputVersion
            }
        } else {
            $version = $inputVersion
            Write-Host "Using specified version: $version"
        }

        $packages = "C:\packages"

        # Install WDK packages for both host and target architectures
        # Host architecture needed for build tools and binaries
        # Target architecture needed for content (libraries, headers)
        $hostWdkPackage = "Microsoft.Windows.WDK.$hostArch"
        $targetWdkPackage = "Microsoft.Windows.WDK.$targetArch"

        # Determine packages to install (avoid duplicates if host == target)
        $packagesToInstall = @($hostWdkPackage)
        if ($targetWdkPackage -ne $hostWdkPackage) {
            $packagesToInstall += $targetWdkPackage
        }

        Write-Host "Installing WDK NuGet packages for version $version..."
        Write-Host "Required packages: $($packagesToInstall -join ', ')"

        foreach ($packageName in $packagesToInstall) {
            Write-Host "Installing $packageName version $version..."
            nuget install $packageName -Version $version -OutputDirectory $packages
            if ($LASTEXITCODE -ne 0) { 
                throw "Failed to install $packageName version $version"
            }
        }

        Write-Host "Successfully installed all WDK packages and dependencies for version $version"

        # Discover installed package paths in packages folder
        Write-Host "Discovering installed package paths..."
        $packageDirs = Get-ChildItem -Path $packages -Directory | Where-Object { $_.Name -like "Microsoft.Windows.*.$sdkVersion.*" }
        Write-Host "Found $($packageDirs.Count) package directories:"
        foreach ($dir in $packageDirs) {
            Write-Host "  - $($dir.Name)"
        }

        # Find all Windows SDK nuget packages
        $sdkPackageDirs = @($packageDirs | Where-Object { $_.Name -like "Microsoft.Windows.SDK.CPP*" })
        Write-Host "Found $($sdkPackageDirs.Count) SDK package(s):"
        foreach ($sdkDir in $sdkPackageDirs) {
            Write-Host "  - $($sdkDir.Name)"
        }
        if ($sdkPackageDirs.Count -eq 0) {
            throw "No SDK packages found in packages folder"
        }

        # Look for the architecture-neutral base package (i.e. without arch suffix)
        $baseSDKPackages = @($sdkPackageDirs | Where-Object { $_.Name -match "^Microsoft\.Windows\.SDK\.CPP\.$sdkVersion(\.\d+)?$" })

        $sdkPackageDir = $null
        if ($baseSDKPackages.Count -eq 1) {
            $sdkPackageDir = $baseSDKPackages[0]
            Write-Host "Using architecture-neutral SDK package: $($sdkPackageDir.Name)"
        } elseif ($baseSDKPackages.Count -gt 1) {
            throw "Multiple architecture-neutral SDK packages found: $($baseSDKPackages.Name -join ', '). Expected exactly one."
        } else {
            throw "No architecture-neutral SDK package found."
        }
        Write-Host "Using Windows SDK (architecture-neutral) directory: $($sdkPackageDir.FullName)"

        # Find all Windows WDK nuget packages
        $wdkPackageDirs = @($packageDirs | Where-Object { $_.Name -like "Microsoft.Windows.WDK*" })
        Write-Host "Found $($wdkPackageDirs.Count) WDK package(s):"
        foreach ($wdkDir in $wdkPackageDirs) {
            Write-Host "  - $($wdkDir.Name)"
        }
        if ($wdkPackageDirs.Count -eq 0) {
            throw "No WDK packages found in packages folder"
        }

        # Find host architecture WDK package
        $hostWdkPackages = @($wdkPackageDirs | Where-Object { $_.Name -match "^Microsoft\.Windows\.WDK\.$hostArch\.$sdkVersion(\.\d+)?$" })
        $hostWdkPackageDir = $null
        if ($hostWdkPackages.Count -eq 1) {
            $hostWdkPackageDir = $hostWdkPackages[0].FullName
            Write-Host "Using WDK host architecture ($hostArch) package: $($hostWdkPackages[0].Name)"
        } elseif ($hostWdkPackages.Count -gt 1) {
            throw "Multiple WDK host packages found for $hostArch architecture: $($hostWdkPackages.Name -join ', '). Expected exactly one."
        } else {
            throw "No WDK host package found for $hostArch architecture."
        }

        # Find target architecture WDK package
        $targetWdkPackages = @($wdkPackageDirs | Where-Object { $_.Name -match "^Microsoft\.Windows\.WDK\.$targetArch\.$sdkVersion(\.\d+)?$" })
        $targetWdkPackageDir = $null
        if ($targetWdkPackages.Count -eq 1) {
            $targetWdkPackageDir = $targetWdkPackages[0].FullName
            Write-Host "Using WDK target architecture ($targetArch) package: $($targetWdkPackages[0].Name)"
        } elseif ($targetWdkPackages.Count -gt 1) {
            throw "Multiple WDK target packages found for $targetArch architecture: $($targetWdkPackages.Name -join ', '). Expected exactly one."
        } else {
            throw "No WDK target package found for $targetArch architecture."
        }

        Write-Host "Using WDK(host-architecture) directory: $hostWdkPackageDir"
        Write-Host "Using WDK(target-architecture) directory: $targetWdkPackageDir"

        $envVars = @{
            "Version_Number" = "$sdkVersion.0"
            "WindowsSdkBinPath" = "$($sdkPackageDir.FullName)\c\bin"
            "WDKContentRoot" = "$targetWdkPackageDir\c\"
            "WDKBinRoot" = "$hostWdkPackageDir\c\bin"
            "WDKToolRoot" = "$hostWdkPackageDir\c\tools"
        }

        # Validate paths exist before setting environment variables
        $paths = @("WindowsSdkBinPath", "WDKContentRoot", "WDKBinRoot", "WDKToolRoot")
        foreach ($pathKey in $paths) {
            $path = $envVars[$pathKey]
            if (-not (Test-Path $path)) {
                throw "Critical path not found: $pathKey = $path"
            }
        }

        $envVars.GetEnumerator() | ForEach-Object {
            Write-Host "Setting $($_.Key) environment variable: $($_.Value)"
            Write-Output "$($_.Key)=$($_.Value)" >> $env:GITHUB_ENV
        }

    - name: Remove existing Windows SDK packages
      if: inputs.source == 'winget'
      uses: ./.github/actions/uninstall-winget-package
      with:
        queries: |
          Microsoft.WindowsSDK
          Windows Software Development Kit

    - name: Remove existing Windows Driver Kit packages
      if: inputs.source == 'winget'
      uses: ./.github/actions/uninstall-winget-package
      with:
        queries: |
          Microsoft.WindowsWDK
          Windows Driver Kit

    - name: Calculate SDK version
      if: inputs.source == 'winget'
      shell: pwsh
      run: |
        Set-StrictMode -Version Latest
        $ErrorActionPreference = 'Stop'

        $inputVersion = '${{ inputs.version }}'
        Write-Host "Processing WDK version: $inputVersion"

        $versionParts = $inputVersion.Split('.')
        $sdkVersion = $versionParts[0..2] -join '.'
        Write-Host "Calculated SDK version: $sdkVersion from input version: $inputVersion"
        Write-Output "SDK_VERSION=$sdkVersion" >> $env:GITHUB_ENV
        Write-Output "Version_Number=$sdkVersion.0" >> $env:GITHUB_ENV

    - name: Install Windows SDK
      if: inputs.source == 'winget'
      uses: ./.github/actions/install-winget-package
      with:
        package-id: Microsoft.WindowsSDK.${{ env.SDK_VERSION }}
        # Workaround for 10.0.22621 SDK installer bug:
        # The installer concatenates long strings to the log path provided by winget, creating paths exceeding 256 chars
        # when winget appends `/log`. Specifying override args explicitly prevents winget from appending `/log`.
        override-args: ${{ (inputs.version == '10.0.22621' || startsWith(inputs.version, '10.0.22621.')) && '/q' || '' }}
        skip-if-installed: "true"
        timeout-minutes: "10"

    - name: Install Windows Driver Kit
      if: inputs.source == 'winget'
      uses: ./.github/actions/install-winget-package
      with:
        package-id: Microsoft.WindowsWDK.${{ inputs.version }}
        skip-if-installed: "true"
        timeout-minutes: "10"
