[package]
name = "cargo-wdk"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
clap = { workspace = true, features = ["derive"] }
cargo_metadata.workspace = true
wdk-build.workspace = true
serde_json.workspace = true
include_dir.workspace = true
clap-verbosity-flag.workspace = true
mockall.workspace = true
# TODO: Plan to move away from these deps
log = "0.4.25"
log4rs = "1.3.0"

[lints.clippy]
unwrap_used = "deny"
