[package]
name = "cargo-wdk"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
thiserror = "2.0.11"
clap = { version = "4.5.27", features = ["derive"] }
include_dir = "0.7.4"
log = "0.4.25"
log4rs = "1.3.0"
toml = "0.8.19"
# wdk-build = "0.3.0"
wdk-build = { git = "https://github.com/svasista-ms/windows-drivers-rs.git", rev = "c0c0f1e254e312da757cdd0cb71c7901a1cb588d" }
cargo_metadata = "0.18.1"
serde_json = "1.0"
clap-verbosity-flag = "3.0.2"
mockall = "0.13.1"

[lints.clippy]
unwrap_used = "deny"
